#!/usr/bin/env ruby
$: << File.join(File.dirname(__FILE__), '.')
#$: << File.join(File.dirname(__FILE__), '..', 'lib')

ARGV.insert(0, ':idl2meta')

require 'ridl/ridl'

if __FILE__ == $0

  IDL.run

end
